### ISSUE TITLE
Colormaps - more than 8 colors!

### ISSUE THREAD

**Issue by Balinus** [Balinus/ClimateTools.jl#23]
Find a way to show more than 8 colors in maps! Still haven't found a way to go higher than the base colormaps. There should be an easy way to interpolate between these colors. The plotting is done using PyPlot/basemap, so I guess the solution should be explored in Python api.

**Comment by Zeitsperre** [comment]
Color ramps via ColorBrewer should be able to handle this I imagine. These colours can be fed into PyPlot/Basemap as well using the Python API.

As a cartographer, I would strongly caution against adding more than 10-11 colours per map. For diverging data (e.g. TAS) you can probably push it that high, but for univariate data on a single gradient, 8 is the maximum number of colours most people can discern.

**Comment by Balinus** [comment]
Interesting. So basically, we could simply leave to 8 colors in the end?

**Comment by Zeitsperre** [comment]
Not necessarily. I may have jumped the gun when it comes to the maximum amount of colours since it really depends on the granularity of the data and what we're trying to show. If we want to show very high resolution data of incrementally changing points (temperatures, precipitation), we can likely get away with hundreds of graded colours on an appropriate ramp, but for distinct categories of data (e.g. integer values for days/dates), 8-10 is usually the limit. 

I imagine that ColorBrewer can at least specify the ramps that we can interpolate from. There must be a similar workflow using it in another Julia-based project.

A gentle introduction to working with climate data and colour: https://earthobservatory.nasa.gov/blogs/elegantfigures/2013/08/05/subtleties-of-color-part-1-of-6/

**Comment by Balinus** [comment]
Found it was much easier than I thought. 4th argument of contourf is the number of colors. Works well for contourf, but for pcolormesh, 8-10 colors is enough.

**Comment by Balinus** [comment]
Closed by 833d75088a8d7d8e71b9185b01db7c299366e2b1

**Comment by Balinus** [comment]
The hack works, but the number of colors returned in the maps are inconsistent with ncolors. For example, setting ncolors=12 returns 13 colors.

**Comment by Balinus** [comment]
I see what's happening. When specifying N, it actually specifies N intervals and thus use N + 1 colors. Perhaps the easiest is to just rename `ncolors` to `nintervals`.
